sudo: required
services:
  - docker

before_install:
  - docker build -t abdulsammad200/docker-react -f Dockerfile.dev .

script:
  - docker run abdulsammad200/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  username: "doramon"
  password: "Doramon123"
  site: "docker-react10"
  on:
    branch: master