version: '3'

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/src/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/usr/src/app
    command: ["npm", "run", "test"]